name: Build and Test

on:
  workflow_call:
    inputs:
      solution_path:
        required: true
        type: string
        description: Path of project for the restore
      coverage_info_file_path:
        required: true
        type: string
        description: Path to coverage file
    secrets:
      code_coverage_token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x' ]

    steps:      
      - uses: actions/checkout@v3
        name: Checkout

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
        name: cache nuget packages

      - name: Install dependencies
        run: dotnet restore ${{ inputs.solution_path }} --locked-mode

      - name: Build
        run: dotnet build ${{ inputs.solution_path }} --configuration Release --no-restore

      - name: Test
        run: dotnet test ${{ inputs.solution_path }} --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov

      - name: Publish coverage report to coveralls.io   
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.code_coverage_token }} 
          path-to-lcov: ${{ inputs.coverage_info_file_path }} 