name: Build and Test

on:
  workflow_call:
    
    inputs:
      solution_path:
        required: true
        type: string
        description: Path of project for the restore

      coverage_info_file_path:
        required: true
        type: string
        description: Path to coverage file

      artifacts_file_path:
        required: true
        type: string
        description: Path for the artifact files/directories

      dotnet_versiosns:
        required: false
        type: string
        default: '6.0.x'
        description: Version of dotnet to be used for build

      include_code_coverage:
        required: false
        type: boolean
        default: true
        description: A flag indicate if the code coverage should be included as part of the build

      upload_artifacts:
        required: false
        type: boolean
        default: true
        description: A flag to indicate weather job will need to upload an artifact

    secrets:
      code_coverage_token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      build_artifact_name: buildArtifacts
    strategy:
      matrix:
        dotnet-version: ['${{inputs.dotnet_versiosns}}']

    steps:      
      - uses: actions/checkout@v3
        name: Checkout

      - name: Setup .net core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'

      - uses: actions/cache@v1
        id: nuget-cache
        with:
          path: ${{ github.workspace }}/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
        name: Cache nuget packages

      - name: Install dependencies
        if: ${{ steps.nuget-cache.outputs.cache-hit != 'true' }}
        run: dotnet restore ${{ inputs.solution_path }} --locked-mode

      - name: Build
        run: dotnet build ${{ inputs.solution_path }} --configuration Release --no-restore

      - name: Test with code coverage
        if: ${{ inputs.include_code_coverage }}
        run: dotnet test ${{ inputs.solution_path }} --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov

      - name: Test without code coverage
        if: ${{ !inputs.include_code_coverage }}
        run: dotnet test ${{ inputs.solution_path }} --no-restore --verbosity normal

      - name: Publish coverage report to coveralls.io
        if: ${{ inputs.include_code_coverage }}  
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.code_coverage_token }} 
          path-to-lcov: ${{ inputs.coverage_info_file_path }} 

      - name: Upload build artifacts
        if: ${{ inputs.upload_artifacts }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.build_artifact_name }}
          path: |
            ${{ inputs.artifacts_file_path }}