name: Continuos integrations and deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ppatel1604/pipeline-demo/.github/workflows/build.yml@main
    with:
      solution_path: ./Web.api/Web.api.sln
      coverage_info_file_path: ./Web.api/Web.api.Tests/TestResults/coverage.info
      build_artifacts_file_path: ./operations
      healthcheck_artifacts_file_path: .github/scripts
    secrets:
      code_coverage_token: ${{ secrets.GITHUB_TOKEN }}

  analysis:
    uses: ppatel1604/pipeline-demo/.github/workflows/codeql.yml@main
    with:
      config_file_path: ./.github/codeql/config.yml

  docker:
    needs: [build]
    uses: ppatel1604/pipeline-demo/.github/workflows/docker.yml@main
    with:
      docker_file_directory: ./Web.api
      docker_repository_name: pipeline-demo
      docker_image_tag: 1.0.0.${{ github.run_number }}
    secrets:
      docker_login_username: ${{ secrets.docker_login_username }}
      docker_login_password: ${{ secrets.docker_login_password }}

  deploy_tst:
    needs: [build, docker]
    uses: ppatel1604/pipeline-demo/.github/workflows/deploy.yml@main
    with:
      resource_group_name: 'tst-pipeline-demo-cac'
      bicep_parameters:  './tst.parameters.json'
      webapp_name: tst-webApp-cac
      docker_image_tag: 1.0.0.${{ github.run_number }}
      docker_repository_name: pipeline-demo
      region: 'canada central'
    secrets:
     azure_credentials: ${{ secrets.azure_credentials }}
     subscription_id: ${{ secrets.subscription_id }}
     docker_login_username: ${{ secrets.docker_login_username }}
     docker_login_password: ${{ secrets.docker_login_password }}
  
  health_check_tst:
    needs: [deploy_tst]
    uses: ./.github/workflows/healthcheck.yml
    with:
      webappUrl: 'https://tst-webapp-cac.azurewebsites.net'

  deploy_stg:
    needs: [deploy_tst]
    uses: ppatel1604/pipeline-demo/.github/workflows/deploy.yml@main
    with:
      resource_group_name: 'stg-pipeline-demo-aus'
      bicep_parameters:  './stg.parameters.json'
      webapp_name: stg-webApp-aus
      docker_image_tag: 1.0.0.${{ github.run_number }}
      docker_repository_name: pipeline-demo
      region: 'australia southeast'
    secrets:
     azure_credentials: ${{ secrets.azure_credentials }}
     subscription_id: ${{ secrets.subscription_id }}
     docker_login_username: ${{ secrets.docker_login_username }}
     docker_login_password: ${{ secrets.docker_login_password }}
  
  health_check_stg:
    needs: [deploy_stg]
    uses: ./.github/workflows/healthcheck.yml
    with:
      webappUrl: 'https://stg-webapp-aus.azurewebsites.net'

  deploy_prd:
    needs: [deploy_stg]
    uses: ppatel1604/pipeline-demo/.github/workflows/deploy.yml@main
    with:
      resource_group_name: 'prd-pipeline-demo-neu'
      bicep_parameters:  './prd.parameters.json'
      webapp_name: prd-webApp-neu
      docker_image_tag: 1.0.0.${{ github.run_number }}
      docker_repository_name: pipeline-demo
      region: 'north europe'
    secrets:
     azure_credentials: ${{ secrets.azure_credentials }}
     subscription_id: ${{ secrets.subscription_id }}
     docker_login_username: ${{ secrets.docker_login_username }}
     docker_login_password: ${{ secrets.docker_login_password }}

  health_check_prd:
    needs: [deploy_prd]
    uses: ./.github/workflows/healthcheck.yml
    with:
      webappUrl: 'https://prd-webapp-neu.azurewebsites.net'
