name: Continuos integrations and deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ppatel1604/pipeline-demo/.github/workflows/build.yml@main
    with:
      solution_path: ./Web.api/Web.api.sln
      coverage_info_file_path: ./Web.api/Web.api.Tests/TestResults/coverage.info
      artifacts_file_path: ./operations
    secrets:
      code_coverage_token: ${{ secrets.GITHUB_TOKEN }}

  analysis:
    uses: ppatel1604/pipeline-demo/.github/workflows/codeql.yml@main
    with:
      config_file_path: ./.github/codeql/config.yml

  docker:
    needs: [build]
    uses: ppatel1604/pipeline-demo/.github/workflows/docker.yml@main
    with:
      docker_file_directory: ./Web.api
      docker_repository_name: pipeline-demo
      docker_image_tag: 1.0.0.${{ github.run_number }}
    secrets:
      docker_login_username: ${{ secrets.docker_login_username }}
      docker_login_password: ${{ secrets.docker_login_password }}

  deploy_tst:
    needs: [build, docker]
    uses: ppatel1604/pipeline-demo/.github/workflows/deploy.yml@main
    with:
      resource_group_name: 'pipeline-demo'
      bicep_parameters:  './buildArtifacts/tst.parameters.json'
      webapp_name: tst-webApp-wus
      docker_image_tag: 1.0.0.${{ github.run_number }}
      docker_repository_name: pipeline-demo
    secrets:
     azure_credentials: ${{ secrets.azure_credentials }}
     subscription_id: ${{ secrets.subscription_id }}
     docker_login_username: ${{ secrets.docker_login_username }}
     docker_login_password: ${{ secrets.docker_login_password }}

  deploy_stg:
    needs: [deploy_tst]
    uses: ppatel1604/pipeline-demo/.github/workflows/deploy.yml@main
    with:
      resource_group_name: 'pipeline-demo'
      bicep_parameters:  './buildArtifacts/stg.parameters.json'
      webapp_name: stg-webApp-wus
      docker_image_tag: 1.0.0.${{ github.run_number }}
      docker_repository_name: pipeline-demo
    secrets:
     azure_credentials: ${{ secrets.azure_credentials }}
     subscription_id: ${{ secrets.subscription_id }}
     docker_login_username: ${{ secrets.docker_login_username }}
     docker_login_password: ${{ secrets.docker_login_password }}

  deploy_prd:
    needs: [deploy_stg]
    uses: ppatel1604/pipeline-demo/.github/workflows/deploy.yml@main
    with:
      resource_group_name: 'pipeline-demo'
      bicep_parameters:  './buildArtifacts/prd.parameters.json'
      webapp_name: prd-webApp-wus
      docker_image_tag: 1.0.0.${{ github.run_number }}
      docker_repository_name: pipeline-demo
    secrets:
     azure_credentials: ${{ secrets.azure_credentials }}
     subscription_id: ${{ secrets.subscription_id }}
     docker_login_username: ${{ secrets.docker_login_username }}
     docker_login_password: ${{ secrets.docker_login_password }}