name: Clean up Infra

on:
  workflow_call:      
    inputs:
      resource_group_name:
        required: true
        type: string
        description: Name of the resource group where the resources will be deployed

    secrets:
      azure_credentials:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Cleanup
    steps:
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.azure_credentials}}
          enable-AzPSSession: true
      
      - name: Check if resource group exists
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Get-AzResourceGroup -Name ${{ inputs.resource_group_name }} -ErrorVariable notPresent -ErrorAction SilentlyContinue
            if (-not $notPresent)
            {
                echo "Resource Group Exists"
                Remove-AzResourceGroup -Name "${{ inputs.resource_group_name }}" -Force
            }
            else
            {
                echo "Resource Group does not Exists. No need to perform cleanup"
            }
          azPSVersion: "latest"
