name: Deploy Infra and Webapp

on:
  workflow_call:      
    inputs:
      resource_group_name:
        required: true
        type: string
        description: Name of the resoruce group where the resources will be deployed

      bicep_parameters:
        required: true
        type: string
        description: Parameters used with the bicep file for deployment

      webapp_name:
        required: true
        type: string
        description: Name of the webapp

      docker_image_tag:
        required: true
        type: string
        description: Docker tag used for the image

      docker_repository_name:
        required: true
        type: string
        description: Docker repository name for the new images

      region:
        required: true
        type: string
        description: Azure region name for the resources

      bicep_file_path:
        required: false
        type: string
        default: './main.bicep'
        description: Azure region name for the resources
      
    secrets:
      azure_credentials:
        required: true

      subscription_id:
        required: true
      
      docker_login_username:
        required: true

      docker_login_password:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/download-artifact@v3
        id: download
        with:
          name: buildArtifacts

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.azure_credentials}}
          enable-AzPSSession: true
      
      - name: Check if resource group exists
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Get-AzResourceGroup -Name ${{ inputs.resource_group_name }} -ErrorVariable notPresent -ErrorAction SilentlyContinue
            if (-not $notPresent)
            {
                echo "Resource Group Exists"
            }
            else
            {
                echo "Resource Group does not Exists"
                echo "create_resource_group=$true" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
            }
          azPSVersion: "latest"

      - name: Create resource group
        if: ${{ env.create_resource_group }}
        uses: azure/powershell@v1
        with:
          inlineScript: |
            New-AzResourceGroup -Name "${{ inputs.resource_group_name }}" -Location "${{ inputs.region }}"
          azPSVersion: "latest"

      - name: Deploy infra
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.subscription_id }}
          resourceGroupName: ${{ inputs.resource_group_name }}
          template: ${{steps.download.outputs.download-path}}/${{ inputs.bicep_file_path }}
          parameters: ${{steps.download.outputs.download-path}}/${{ inputs.bicep_parameters }}
          failOnStdErr: false
          deploymentName: 'Deployment_${{ inputs.docker_image_tag }}'

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.docker_login_username }}
          password: ${{ secrets.docker_login_password }}

      - name: Deploy webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ inputs.webapp_name }}
          images: ${{ secrets.docker_login_username }}/${{ inputs.docker_repository_name }}:${{ inputs.docker_image_tag }}