name: Docker Build and Push

on:
  workflow_call:
    
    inputs:
      docker_file_directory:
        required: true
        type: string
        description: Directory path to docker file

      docker_image_tag:
        required: true
        type: string
        description: Docker tag used for the image

      docker_repository_name:
        required: true
        type: string
        description: Docker repository name for the new images

    secrets:
      docker_login_username:
        required: true

      docker_login_password:
        required: true

jobs:
  build:
    runs-on: [self-hosted, linux]
    
    steps:      
      - uses: actions/checkout@v3
        name: Checkout

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.docker_login_username }}
          password: ${{ secrets.docker_login_password }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.docker_file_directory }}
          push: true
          tags: ${{ secrets.docker_login_username }}/${{ inputs.docker_repository_name }}:${{ inputs.docker_image_tag }}
          cache-from: type=registry,ref=${{ secrets.docker_login_username }}/${{ inputs.docker_repository_name }}:buildcache
          cache-to: type=registry,ref=${{ secrets.docker_login_username }}/${{ inputs.docker_repository_name }}:buildcache,mode=max