name: Deploy Infrastructure

on:
  workflow_call:      
    inputs:
      resource_group_name:
        required: true
        type: string
        description: Name of the resoruce group where the resources will be deployed

      region:
        required: false
        type: string
        default: 'west us'
        description: Azure region name for the resources
      
    secrets:
      azure_credentials:
        required: true
      subscription_id:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/download-artifact@v3
        
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.azure_credentials}}
          enable-AzPSSession: true
      
      - name: Check resource group
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Get-AzResourceGroup -Name ${{ inputs.resource_group_name }} -ErrorVariable notPresent -ErrorAction SilentlyContinue
            if ($notPresent)
            {
                echo "Resource Group Exists"
            }
            else
            {
                echo "Resource Group does not Exists"
                echo "create_resource_group=$true" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
            }
          azPSVersion: "latest"

      - name: Create resource group
        if: ${{ env.create_resource_group }}
        uses: azure/powershell@v1
        with:
          inlineScript: |
            New-AzResourceGroup -Name ${{ inputs.resource_group_name }} -Location ${{ inputs.region }}
          azPSVersion: "latest"

      - name: Deploy infra
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.subscription_id }}
          resourceGroupName: ${{ inputs.resource_group_name }}
          template: ./main.bicep
          parameters: ./dev.parameters.json
          failOnStdErr: false

      
        