name: Deploy Infrastructure

on:
  workflow_call:      

    secrets:
      azure_credentials:
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/download-artifact@v3
        
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.azure_credentials}}
          enable-AzPSSession: true
      
      - name: Check resource group
        run: |
          $resourceGroup = Get-AzResourceGroup -Name "pipeline-demo"
          echo $resourceGroup
        shell: powershell