name: pull request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ppatel1604/pipeline-demo/.github/workflows/build.yml
    with:
      solution_path: ./Web.api/Web.api.sln
      coverage_info_file_path: ./Web.api/Web.api.Tests/TestResults/coverage.info
      build_artifacts_file_path: ./operations
      healthcheck_artifacts_file_path: .github/scripts
    secrets:
      code_coverage_token: ${{ secrets.GITHUB_TOKEN }}

  analysis:
    uses: ppatel1604/pipeline-demo/.github/workflows/codeql.yml
    with:
      config_file_path: ./.github/codeql/config.yml

  docker:
    needs: [build]
    uses: ppatel1604/pipeline-demo/.github/workflows/docker.yml@healthcheck
    with:
      docker_file_directory: ./Web.api
      docker_repository_name: pipeline-demo
      docker_image_tag: 0.0.0.${{ github.run_number }}
    secrets:
      docker_login_username: ${{ secrets.docker_login_username }}
      docker_login_password: ${{ secrets.docker_login_password }}

  deploy_infra:
    needs: [build, docker]
    uses: ppatel1604/pipeline-demo/.github/workflows/deploy.yml
    with:
      resource_group_name: 'dev-pipeline-demo-wus'
      bicep_parameters:  './dev.parameters.json'
      webapp_name: dev-webApp-wus
      docker_image_tag: 0.0.0.${{ github.run_number }}
      docker_repository_name: pipeline-demo
      region: 'west us'
    secrets:
     azure_credentials: ${{ secrets.azure_credentials }}
     subscription_id: ${{ secrets.subscription_id }}
     docker_login_username: ${{ secrets.docker_login_username }}
     docker_login_password: ${{ secrets.docker_login_password }}

  health_check:
    needs: deploy_infra
    uses: ppatel1604/pipeline-demo/.github/workflows/healthcheck.yml
    with:
      webappUrl: 'https://dev-webapp-wus.azurewebsites.net'

  cleanup_infra:
    needs: [deploy_infra, health_check]
    uses: ppatel1604/pipeline-demo/.github/workflows/cleanup.yml
    with:
      resource_group_name: 'dev-pipeline-demo-wus'
    secrets:
      azure_credentials: ${{ secrets.azure_credentials }}