name: pull request

on: [push]

jobs:
  build:
    uses: ppatel1604/pipeline-demo/.github/workflows/build.yml@docker-build
    with:
      solution_path: ./Web.api/Web.api.sln
      coverage_info_file_path: ./Web.api/Web.api.Tests/TestResults/coverage.info
      artifacts_file_path: ./operations
    secrets:
      code_coverage_token: ${{ secrets.GITHUB_TOKEN }}
      docker_login_username: ${{ secrets.docker_login_username }}
      docker_login_password: ${{ secrets.docker_login_password }}

  analysis:
    uses: ppatel1604/pipeline-demo/.github/workflows/codeql.yml@docker-build
    with:
      config_file_path: ./.github/codeql/config.yml

  docker:
    needs: [build, analysis]
    uses: ppatel1604/pipeline-demo/.github/workflows/docker.yml@docker-build
    with:
      docker_file_directory: ./Web.api
      docker_repository_name: pipeline-demo
      docker_image_tag: 0.0.0.${{ github.run_number }}
    secrets:
      docker_login_username: ${{ secrets.docker_login_username }}
      docker_login_password: ${{ secrets.docker_login_password }}