name: pull request

on: [push]

jobs:
  build:
    uses: ppatel1604/pipeline-demo/.github/workflows/build.yml@pr-workflow
    with:
      solution_path: ./Web.api/Web.api.sln
      coverage_info_file_path: ./Web.api/Web.api.Tests/TestResults/coverage.info
    secrets:
      code_coverage_token: ${{ secrets.GITHUB_TOKEN }}