name: pull request

on:
  pull_request:
    branches:
      - main

env:
  major_version: '0'
  minor_version: '0.0'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Variables
        id: set_output
        run: |
          VERSION=${{ env.major_version }}.${{ env.minor_version }}.$GITHUB_RUN_NUMBER
          echo "Version Number: $VERSION"
          echo "::set-output name=DOCKER_REPOSITORY_NAME::pipeline-demo"
          echo "::set-output name=VERSION::$VERSION"
    outputs:
      docker_repository_name: ${{ steps.set_output.outputs.docker_repository_name }}
      version: ${{ steps.set_output.outputs.version }}

  build:
    uses: ./.github/workflows/build.yml
    with:
      solution_path: ./Web.api/Web.api.sln
      coverage_info_file_path: ./Web.api/Web.api.Tests/TestResults/coverage.info
      build_artifacts_file_path: ./operations
      healthcheck_artifacts_file_path: .github/scripts
    secrets:
      code_coverage_token: ${{ secrets.GITHUB_TOKEN }}

  analysis:
    uses: ./.github/workflows/codeql.yml
    with:
      config_file_path: ./.github/codeql/config.yml

  docker:
    needs: [build, setup]
    uses: ./.github/workflows/docker.yml
    with:
      docker_file_directory: ./Web.api
      docker_repository_name: ${{ needs.setup.outputs.docker_repository_name }}
      docker_image_tag: ${{ needs.setup.outputs.version }}
    secrets:
      docker_login_username: ${{ secrets.docker_login_username }}
      docker_login_password: ${{ secrets.docker_login_password }}

  deploy_infra:
    needs: [build, docker, setup]
    uses: ./.github/workflows/deploy.yml
    with:
      resource_group_name: 'dev-pipeline-demo-wus'
      bicep_parameters:  './dev.parameters.json'
      webapp_name: dev-webApp-wus
      docker_image_tag: ${{ needs.setup.outputs.docker_repository_name }}
      docker_repository_name: ${{ needs.setup.outputs.version }}
      region: 'west us'
    secrets:
     azure_credentials: ${{ secrets.azure_credentials }}
     subscription_id: ${{ secrets.subscription_id }}
     docker_login_username: ${{ secrets.docker_login_username }}
     docker_login_password: ${{ secrets.docker_login_password }}

  health_check:
    needs: deploy_infra
    uses: ./.github/workflows/healthcheck.yml
    with:
      webappUrl: 'https://dev-webapp-wus.azurewebsites.net'

  cleanup_infra:
    needs: [deploy_infra, health_check]
    uses: ./.github/workflows/cleanup.yml
    with:
      resource_group_name: 'dev-pipeline-demo-wus'
    secrets:
      azure_credentials: ${{ secrets.azure_credentials }}